CC = gcc
GFLAGS = -lpthread
LIB = -L/usr/local/lib -lssl -lcrypto

all: server client

%.o: %.c myftp.h 
	${CC} $< -c

server: myftpserver.o myftp.o 
	${CC} -o myftpserver myftpserver.o myftp.o $(GFLAGS) $(LIB)

client: myftpclient.o myftp.o 
	${CC} -o myftpclient myftpclient.o myftp.o $(GFLAGS) $(LIB)

clean:
	rm *.o
